"""PDF rendering for EU AI Act Article 11 Technical Documentation.

Layout:
  Page 1 — Cover (color-coded risk banner, agent name, generation date, doc title).
  Page 2 — Table of Contents.
  Pages 3..N — One page per Article 11 section (9 total).
  Page N+1 — Fundamental Rights Impact Assessment (FRIA) summary.
  Page N+2 — Datasheet appendix (model-card style table).

Every page after the cover carries a small header (document title) plus a
footer with `FOOTER_TEXT` and "Page X of Y". Page numbering is added by a
two-pass NumberedCanvas so totals are accurate.
"""

from __future__ import annotations

import os
from typing import Any, Callable

from reportlab.lib.colors import HexColor, white
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as _canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas import RiskTier, TechnicalFile

PAGE_W, PAGE_H = LETTER
MARGIN = 0.75 * inch

DOC_TITLE = "EU AI Act Article 11 Technical Documentation"
FOOTER_TEXT = (
    "Generated by ComplyForge | Not legal advice | Article 11 + Annex IV mapping"
)

# Hex values match the the architecture spec frontend palette so the PDF banner
# matches the dashboard tier badges.
RISK_TIER_COLORS: dict[RiskTier, str] = {
    RiskTier.PROHIBITED: "#DC2626",   # red
    RiskTier.HIGH_RISK: "#EA580C",    # orange
    RiskTier.LIMITED_RISK: "#CA8A04", # amber
    RiskTier.MINIMAL_RISK: "#16A34A", # green
}

RISK_TIER_LABELS: dict[RiskTier, str] = {
    RiskTier.PROHIBITED: "PROHIBITED",
    RiskTier.HIGH_RISK: "HIGH RISK",
    RiskTier.LIMITED_RISK: "LIMITED RISK",
    RiskTier.MINIMAL_RISK: "MINIMAL RISK",
}


def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "CFTitle", parent=base["Title"], fontSize=22, leading=26,
            alignment=TA_CENTER, textColor=HexColor("#111827"), spaceAfter=10,
        ),
        "subtitle": ParagraphStyle(
            "CFSubtitle", parent=base["Heading2"], fontSize=13, leading=18,
            alignment=TA_CENTER, textColor=HexColor("#374151"), spaceAfter=6,
        ),
        "heading": ParagraphStyle(
            "CFHeading", parent=base["Heading1"], fontSize=16, leading=20,
            alignment=TA_LEFT, textColor=HexColor("#111827"),
            spaceBefore=4, spaceAfter=10,
        ),
        "body": ParagraphStyle(
            "CFBody", parent=base["BodyText"], fontSize=10.5, leading=14,
            alignment=TA_JUSTIFY, textColor=HexColor("#1F2937"), spaceAfter=8,
        ),
        "small": ParagraphStyle(
            "CFSmall", parent=base["BodyText"], fontSize=9, leading=12,
            alignment=TA_CENTER, textColor=HexColor("#4B5563"),
        ),
        "toc": ParagraphStyle(
            "CFToc", parent=base["BodyText"], fontSize=11, leading=16,
            textColor=HexColor("#1F2937"),
        ),
    }


class _NumberedCanvas(_canvas.Canvas):
    """Canvas subclass that adds 'Page X of Y' + footer text on every page."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_pages: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_pages.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        total = len(self._saved_pages)
        for state in self._saved_pages:
            self.__dict__.update(state)
            self._draw_footer(total)
            super().showPage()
        super().save()

    def _draw_footer(self, total: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(HexColor("#6B7280"))
        self.drawString(MARGIN, 0.4 * inch, FOOTER_TEXT)
        self.drawRightString(
            PAGE_W - MARGIN,
            0.4 * inch,
            f"Page {self._pageNumber} of {total}",
        )
        self.restoreState()


class PDFGenerator:
    """Render a `TechnicalFile` to a multi-page PDF on disk."""

    BANNER_HEIGHT = 2.8 * inch

    def render_technical_file(
        self, tech_file: TechnicalFile, output_path: str,
    ) -> str:
        directory = os.path.dirname(output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

        styles = _build_styles()

        body_frame = Frame(
            MARGIN, MARGIN,
            PAGE_W - 2 * MARGIN, PAGE_H - 2 * MARGIN,
            id="body", showBoundary=0,
        )
        cover_template = PageTemplate(
            id="cover", frames=[body_frame],
            onPage=self._make_cover_painter(tech_file),
        )
        body_template = PageTemplate(
            id="content", frames=[body_frame],
            onPage=self._draw_running_header,
        )

        doc = BaseDocTemplate(
            output_path,
            pagesize=LETTER,
            leftMargin=MARGIN, rightMargin=MARGIN,
            topMargin=MARGIN, bottomMargin=MARGIN,
            title=DOC_TITLE,
            author="ComplyForge",
        )
        doc.addPageTemplates([cover_template, body_template])

        story: list[Any] = []
        story.extend(self._cover_flowables(tech_file, styles))
        story.append(NextPageTemplate("content"))
        story.append(PageBreak())
        story.extend(self._toc_flowables(tech_file, styles))
        story.append(PageBreak())

        for idx, section in enumerate(tech_file.sections):
            story.extend(self._section_flowables(section, styles))
            story.append(PageBreak())

        story.extend(self._fria_flowables(tech_file, styles))
        story.append(PageBreak())
        story.extend(self._datasheet_flowables(tech_file, styles))

        doc.build(story, canvasmaker=_NumberedCanvas)
        return output_path

    # ------------------------------------------------------------------
    # Page-decoration painters
    # ------------------------------------------------------------------
    def _make_cover_painter(self, tech_file: TechnicalFile) -> Callable[..., None]:
        color_hex = RISK_TIER_COLORS[tech_file.risk_tier]
        label = RISK_TIER_LABELS[tech_file.risk_tier]
        banner_h = self.BANNER_HEIGHT

        def _paint(canvas: _canvas.Canvas, _doc: Any) -> None:
            canvas.saveState()
            canvas.setFillColor(HexColor(color_hex))
            canvas.rect(0, PAGE_H - banner_h, PAGE_W, banner_h, fill=1, stroke=0)
            canvas.setFillColor(white)
            canvas.setFont("Helvetica-Bold", 30)
            canvas.drawCentredString(PAGE_W / 2, PAGE_H - 1.2 * inch, "ComplyForge")
            canvas.setFont("Helvetica", 13)
            canvas.drawCentredString(
                PAGE_W / 2, PAGE_H - 1.6 * inch,
                "EU AI Act Compliance Co-Pilot",
            )
            canvas.setFont("Helvetica-Bold", 28)
            canvas.drawCentredString(
                PAGE_W / 2, PAGE_H - 2.35 * inch,
                f"Risk Tier: {label}",
            )
            canvas.restoreState()

        return _paint

    @staticmethod
    def _draw_running_header(canvas: _canvas.Canvas, _doc: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(HexColor("#6B7280"))
        canvas.drawString(MARGIN, PAGE_H - 0.4 * inch, DOC_TITLE)
        canvas.restoreState()

    # ------------------------------------------------------------------
    # Flowable builders
    # ------------------------------------------------------------------
    @staticmethod
    def _cover_flowables(tech_file: TechnicalFile, styles: dict[str, ParagraphStyle]) -> list[Any]:
        gen_date = tech_file.generated_at.strftime("%Y-%m-%d %H:%M UTC")
        story: list[Any] = [Spacer(1, 2.7 * inch)]
        story.append(Paragraph(DOC_TITLE, styles["title"]))
        story.append(Spacer(1, 0.15 * inch))
        story.append(Paragraph(
            f"<b>Agent:</b> {_xml(tech_file.agent_name)}", styles["subtitle"],
        ))
        story.append(Paragraph(f"<b>Generated:</b> {gen_date}", styles["subtitle"]))
        story.append(Spacer(1, 0.4 * inch))
        story.append(Paragraph(
            "Prepared in accordance with Regulation (EU) 2024/1689 "
            "(&#8216;EU AI Act&#8217;), Article 11 and Annex IV. This document is for "
            "informational purposes only and does not constitute legal advice.",
            styles["small"],
        ))
        return story

    @staticmethod
    def _toc_flowables(tech_file: TechnicalFile, styles: dict[str, ParagraphStyle]) -> list[Any]:
        story: list[Any] = [Paragraph("Table of Contents", styles["heading"])]
        for idx, s in enumerate(tech_file.sections, start=1):
            story.append(Paragraph(f"{idx}. {_xml(s.heading)}", styles["toc"]))
        n = len(tech_file.sections)
        story.append(Paragraph(
            f"{n + 1}. Fundamental Rights Impact Assessment (FRIA)", styles["toc"],
        ))
        story.append(Paragraph(
            f"{n + 2}. Datasheet (Appendix)", styles["toc"],
        ))
        return story

    @staticmethod
    def _section_flowables(section: Any, styles: dict[str, ParagraphStyle]) -> list[Any]:
        story: list[Any] = [Paragraph(_xml(section.heading), styles["heading"])]
        for para in _split_paragraphs(section.body):
            story.append(Paragraph(para, styles["body"]))
        return story

    @staticmethod
    def _fria_flowables(tech_file: TechnicalFile, styles: dict[str, ParagraphStyle]) -> list[Any]:
        story: list[Any] = [Paragraph(
            "Fundamental Rights Impact Assessment (FRIA)", styles["heading"],
        )]
        for para in _split_paragraphs(tech_file.fria_summary):
            story.append(Paragraph(para, styles["body"]))
        return story

    @staticmethod
    def _datasheet_flowables(tech_file: TechnicalFile, styles: dict[str, ParagraphStyle]) -> list[Any]:
        story: list[Any] = [Paragraph("Datasheet — Appendix", styles["heading"])]
        rows: list[list[Any]] = [["Field", "Value"]]
        for key, value in tech_file.datasheet.items():
            field_label = key.replace("_", " ").title()
            value_para = Paragraph(_xml(str(value)), styles["body"])
            rows.append([field_label, value_para])
        table = Table(rows, colWidths=[1.7 * inch, 4.8 * inch], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                [HexColor("#F9FAFB"), HexColor("#FFFFFF")]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E5E7EB")),
        ]))
        story.append(table)
        return story


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def _xml(text: str) -> str:
    """Minimal XML escape so user content can't break reportlab Paragraph parsing."""
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
    )


def _split_paragraphs(text: str) -> list[str]:
    if not text or not text.strip():
        return ["(No content provided.)"]
    normalised = text.replace("\r\n", "\n").replace("\r", "\n")
    parts = [p.strip() for p in normalised.split("\n\n") if p.strip()]
    if not parts:
        parts = [normalised.strip()]
    return [_xml(p) for p in parts]


__all__ = [
    "PDFGenerator",
    "RISK_TIER_COLORS",
    "RISK_TIER_LABELS",
    "FOOTER_TEXT",
    "DOC_TITLE",
]
