import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { Download, ExternalLink, FileText, Package } from 'lucide-react'
import RiskBadge from '../components/RiskBadge'
import { useInventory } from '../store/inventory'
import { getInventoryZipUrl, getPdfUrl } from '../api/client'
import { basename, relativeTime } from '../lib/format'

const TIER_BG = {
  prohibited: 'bg-risk-prohibited',
  high_risk: 'bg-risk-high',
  limited_risk: 'bg-risk-limited',
  minimal_risk: 'bg-risk-minimal',
}

export default function DocsLibrary() {
  const reports = useInventory((s) => s.reports)
  const list = useMemo(
    () => Object.values(reports).filter((r) => r.pdf_path),
    [reports],
  )

  const zipUrl = getInventoryZipUrl()

  if (Object.keys(reports).length === 0) {
    return (
      <div className="space-y-4">
        <h1 className="text-2xl font-semibold text-text-main">Docs Library</h1>
        <div className="rounded-xl border border-dashed border-border-soft bg-bg-panel p-10 text-center">
          <p className="text-sm text-text-dim">
            No analyses yet. Start with a sample agent.
          </p>
          <Link
            to="/analyze"
            className="mt-4 inline-flex items-center gap-2 rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg-base hover:bg-accent/90"
          >
            New Analysis
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-text-main">Docs Library</h1>
          <p className="text-sm text-text-dim">
            Article 11 / Annex IV technical files generated by ComplyForge.
          </p>
        </div>
        <a
          href={zipUrl}
          download="complyforge-inventory.zip"
          className="inline-flex items-center gap-2 rounded-md border border-border-soft px-3 py-1.5 text-xs text-text-main hover:bg-border-soft/40"
          title="Stream every PDF + JSON report as a ZIP"
        >
          <Package size={14} /> Download all as ZIP
        </a>
      </header>

      {list.length === 0 ? (
        <div className="rounded-xl border border-dashed border-border-soft bg-bg-panel p-10 text-center">
          <p className="text-sm text-text-dim">
            No PDFs yet. Re-run analyses with the orchestrator to render
            technical files.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {list.map((r) => (
            <DocCard key={r.agent.name} report={r} />
          ))}
        </div>
      )}
    </div>
  )
}

function DocCard({ report }) {
  const tier = report.classification?.tier
  const file = basename(report.pdf_path)
  const pdfUrl = file ? getPdfUrl(file) : null
  return (
    <article className="overflow-hidden rounded-xl border border-border-soft bg-bg-panel">
      <div
        className={[
          'flex h-24 items-center justify-center',
          TIER_BG[tier] || 'bg-border-soft',
        ].join(' ')}
      >
        <FileText size={36} className="text-white" aria-hidden="true" />
      </div>
      <div className="space-y-3 p-4">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <div className="truncate font-semibold text-text-main">
              {report.agent.name}
            </div>
            <div className="text-xs text-text-dim">
              {relativeTime(report.technical_file?.generated_at)}
            </div>
          </div>
          <RiskBadge tier={tier} size="sm" />
        </div>
        <div className="font-mono text-xs text-text-dim">{file || '—'}</div>
        <div className="flex items-center gap-2">
          {pdfUrl ? (
            <>
              <a
                href={pdfUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-md bg-accent px-3 py-1.5 text-xs font-semibold text-bg-base hover:bg-accent/90"
              >
                <ExternalLink size={12} /> Open
              </a>
              <a
                href={pdfUrl}
                download={file}
                className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-md border border-border-soft px-3 py-1.5 text-xs text-text-main hover:bg-border-soft/40"
              >
                <Download size={12} /> Download
              </a>
            </>
          ) : (
            <span className="text-xs text-text-dim">PDF not generated.</span>
          )}
        </div>
      </div>
    </article>
  )
}
